import type { GlossaryCategory, GlossaryTerm } from '../types'

export const GLOSSARY_CATEGORIES: GlossaryCategory[] = [
  'Engineering & Technical',
  'Design & UX',
  'Process & Agile',
  'Data & Metrics',
  'Product & Growth',
]

export const GLOSSARY: GlossaryTerm[] = [
  // Engineering & Technical
  {
    term: 'API (Application Programming Interface)',
    category: 'Engineering & Technical',
    definition:
      "A defined way for one piece of software to request functionality or data from another. Think of it like a power outlet: you don’t need to know how the electricity is generated, you just need the right plug to draw from it.",
  },
  {
    term: 'Architecture',
    category: 'Engineering & Technical',
    definition:
      'The overall technical design of a system: which technologies are used, how the pieces fit together, and the trade-offs made to deliver a particular experience.',
  },
  {
    term: 'Backend',
    category: 'Engineering & Technical',
    definition:
      'The parts of an application that run on servers rather than in the browser, handling the logic, data, and requests that power what a user sees.',
  },
  {
    term: 'Beta Testing',
    category: 'Engineering & Technical',
    definition:
      'Releasing a near-final version of a product to a limited group of real users before a full public launch, to catch issues and gather feedback while the stakes are still small.',
  },
  {
    term: 'Branches',
    category: 'Engineering & Technical',
    definition:
      "Parallel copies of a codebase that let engineers work on different pieces of a feature at the same time without disrupting the main, stable version.",
  },
  {
    term: 'Bug',
    category: 'Engineering & Technical',
    definition: 'An instance where software behaves differently than intended.',
  },
  {
    term: 'Build Pipeline',
    category: 'Engineering & Technical',
    definition:
      "The automated sequence a codebase moves through — compiling, testing, packaging — before it’s ready to be released.",
  },
  {
    term: 'Caching',
    category: 'Engineering & Technical',
    definition:
      'Temporarily storing frequently accessed data somewhere fast to retrieve, so the system doesn’t have to fetch or recompute it from scratch every time.',
  },
  {
    term: 'CI/CD (Continuous Integration / Continuous Delivery)',
    category: 'Engineering & Technical',
    definition:
      'Automated systems that test and ship code changes frequently and reliably, rather than in large, risky, infrequent batches.',
  },
  {
    term: 'Client-Side',
    category: 'Engineering & Technical',
    definition:
      "Code that runs in the user’s browser rather than on a server, typically anything the user directly sees and interacts with.",
  },
  {
    term: 'Cloud Service Provider',
    category: 'Engineering & Technical',
    definition:
      "A company (AWS, Google Cloud, Azure, and similar) that rents out computing infrastructure, so engineering teams don’t have to buy and maintain physical servers themselves.",
  },
  {
    term: 'Database',
    category: 'Engineering & Technical',
    definition:
      "Organised storage for an application’s data, structured so it can be reliably saved, queried, and updated.",
  },
  {
    term: 'Deployment',
    category: 'Engineering & Technical',
    definition: 'The act of publishing a new version of an application so it becomes the version currently running.',
  },
  {
    term: 'Feature Flag',
    category: 'Engineering & Technical',
    definition:
      "A switch inside the codebase that lets a team turn a feature on or off for specific users without a new deployment — useful for gradual rollouts and fast rollbacks.",
  },
  {
    term: 'Front End',
    category: 'Engineering & Technical',
    definition: 'The user-facing part of a product: the screens, layouts, and interactions a user directly experiences.',
  },
  {
    term: 'GitHub',
    category: 'Engineering & Technical',
    definition: 'Where engineering teams store, version, and collaborate on code, with a full history of every change ever made.',
  },
  {
    term: 'Infrastructure',
    category: 'Engineering & Technical',
    definition:
      'The underlying technical building blocks — servers, databases, storage, networking — that a product is built on top of.',
  },
  {
    term: 'Latency',
    category: 'Engineering & Technical',
    definition: "The delay between a user’s action and the system’s response. The lower it is, the snappier a product feels.",
  },
  {
    term: 'Logs',
    category: 'Engineering & Technical',
    definition:
      'Records automatically generated by a system describing what it did and when, used to debug issues or reconstruct what happened after the fact.',
  },
  {
    term: 'Pull Request (PR)',
    category: 'Engineering & Technical',
    definition: "A formal request for a code change to be reviewed by teammates before it’s merged into the main codebase.",
  },
  {
    term: 'QA (Quality Assurance)',
    category: 'Engineering & Technical',
    definition:
      "The discipline — and often the team — responsible for catching bugs and verifying a release actually works as intended before it ships.",
  },
  {
    term: 'Refactoring',
    category: 'Engineering & Technical',
    definition: "Cleaning up or restructuring existing code to make it clearer and easier to maintain, without changing what it actually does.",
  },
  {
    term: 'Regression',
    category: 'Engineering & Technical',
    definition:
      'A bug that reintroduces a problem that had previously been fixed, usually as an unintended side effect of a later change.',
  },
  {
    term: 'Release',
    category: 'Engineering & Technical',
    definition: 'The point at which a new version of a product becomes available to users.',
  },
  {
    term: 'Repository (“repo”)',
    category: 'Engineering & Technical',
    definition: 'A dedicated storage location (typically on GitHub) containing all the code for a particular application or service.',
  },
  {
    term: 'Rollback',
    category: 'Engineering & Technical',
    definition:
      'Reverting a live release back to its previous working version, usually done fast when a new release causes serious problems.',
  },
  {
    term: 'Runtime',
    category: 'Engineering & Technical',
    definition:
      "The period during which a program is actually executing, as opposed to when it’s being written or compiled — and the environment that supports that execution.",
  },
  {
    term: 'Scalability',
    category: 'Engineering & Technical',
    definition: "A system’s ability to keep working well as usage grows, without falling over or slowing to a crawl.",
  },
  {
    term: 'Server',
    category: 'Engineering & Technical',
    definition: "A computer that stores an application’s code and processes requests from users' browsers or devices.",
  },
  {
    term: 'Staging Environment',
    category: 'Engineering & Technical',
    definition: 'A near-identical copy of the live product used to test changes safely before they reach real users.',
  },
  {
    term: 'Technical Debt',
    category: 'Engineering & Technical',
    definition:
      "The accumulated cost of code that’s messy, poorly designed, or hastily built. It’s not necessarily wrong — it just slows down every future change until someone addresses it.",
    seeAlso: { to: '/day/4', label: 'Day 4' },
  },
  {
    term: 'Unit Testing',
    category: 'Engineering & Technical',
    definition:
      'Small, automated tests engineers write to check that individual pieces of code work as expected, without manually re-checking everything by hand each time something changes.',
  },
  {
    term: 'Uptime / SLA',
    category: 'Engineering & Technical',
    definition:
      'The percentage of time a system is actually available and working, often backed by a formal Service Level Agreement promising a minimum threshold.',
  },

  // Design & UX
  {
    term: 'Accessibility (a11y)',
    category: 'Design & UX',
    definition:
      'Designing a product so people with disabilities — visual, motor, auditory, cognitive — can use it too. Not an afterthought; a baseline requirement.',
  },
  {
    term: 'Design System',
    category: 'Design & UX',
    definition:
      'A shared library of reusable components, patterns, and rules (colour, type, spacing) that keeps a product visually and functionally consistent as many people build it.',
  },
  {
    term: 'Empathy Map',
    category: 'Design & UX',
    definition:
      "A simple exercise that organises what’s known about a user into what they say, think, feel, and do — a fuller picture than a persona’s bio alone.",
  },
  {
    term: 'Fidelity (Low / High)',
    category: 'Design & UX',
    definition:
      'How close a design artifact is to the finished product. Low fidelity (a wireframe) is rough and fast; high fidelity (a polished mockup or prototype) looks, and often behaves, like the real thing.',
  },
  {
    term: 'Heuristic Evaluation',
    category: 'Design & UX',
    definition:
      'An expert review of an interface against a known set of usability principles, done without recruiting real users — fast and cheap, though no substitute for actual testing.',
  },
  {
    term: 'Information Architecture (IA)',
    category: 'Design & UX',
    definition:
      "How content and features are structured and labelled so users can actually find what they need — the skeleton a wireframe sits on top of.",
  },
  {
    term: 'Mockups',
    category: 'Design & UX',
    definition: "Higher-fidelity, static visual representations of an interface — further along than a wireframe, but not yet interactive.",
  },
  {
    term: 'Personas',
    category: 'Design & UX',
    definition: 'Fictional individuals, built from real user research, used to represent a specific target user group.',
    seeAlso: { to: '/day/2', label: 'Day 2' },
  },
  {
    term: 'Prototype',
    category: 'Design & UX',
    definition:
      'An interactive, testable stand-in for a real product, used to validate ideas with real users before committing engineering time to the finished version.',
  },
  {
    term: 'Stakeholder Interviews',
    category: 'Design & UX',
    definition:
      "Structured conversations with people who have a stake in a project’s outcome, used to surface constraints, expectations, and context before or during design work.",
  },
  {
    term: 'UI (User Interface)',
    category: 'Design & UX',
    definition: 'The specific visual and interactive surface a user touches: buttons, screens, layout, colour, typography.',
  },
  {
    term: 'Usability Test',
    category: 'Design & UX',
    definition: 'Watching a real person attempt real tasks in a product to find out where they struggle, before those struggles reach every user.',
  },
  {
    term: 'User Journey',
    category: 'Design & UX',
    definition:
      'The end-to-end path a user takes through a product or service, from first contact through to whatever comes after, often mapped to spot friction points.',
  },
  {
    term: 'UX (User Experience)',
    category: 'Design & UX',
    definition:
      'The overall quality of a person’s experience using a product: how easy, useful, and satisfying it is, not just how it looks.',
  },
  {
    term: 'Wireframe',
    category: 'Design & UX',
    definition: "A low-fidelity, structural sketch of an interface’s layout and content, deliberately stripped of visual design.",
    seeAlso: { to: '/day/3', label: 'Day 3' },
  },

  // Process & Agile
  {
    term: 'Agile',
    category: 'Process & Agile',
    definition:
      'An approach to building software in small, frequent iterations with continuous feedback, rather than planning the entire product upfront and building it in one long pass.',
  },
  {
    term: 'Backlog',
    category: 'Process & Agile',
    definition:
      "The full, ranked list of everything a team could work on next — deliberately more than will actually get built, so there’s always a prioritised queue to pull from.",
  },
  {
    term: 'Definition of Done',
    category: 'Process & Agile',
    definition:
      "A team’s agreed, explicit checklist for when a piece of work actually counts as finished — not just coded, but tested, reviewed, and ready for users.",
  },
  {
    term: 'Epic',
    category: 'Process & Agile',
    definition: 'A large body of work too big to fit in one sprint, broken down into a set of smaller, individually shippable user stories.',
  },
  {
    term: 'Kanban',
    category: 'Process & Agile',
    definition:
      'A visual, continuous-flow way of managing work as it moves through stages (like To Do → In Progress → Done), without the fixed time-boxes of Scrum.',
  },
  {
    term: 'Retrospective',
    category: 'Process & Agile',
    definition:
      "A recurring meeting, usually at the end of a sprint, where a team reflects on what worked, what didn’t, and what to change going forward.",
  },
  {
    term: 'Scrum',
    category: 'Process & Agile',
    definition:
      'A specific, structured way of running agile work in fixed-length sprints, with defined roles (Product Owner, Scrum Master, the team) and ceremonies (planning, standup, review, retrospective).',
  },
  {
    term: 'Sprint',
    category: 'Process & Agile',
    definition: 'A fixed, short time period — commonly one to two weeks — during which a team commits to completing a defined set of work.',
  },
  {
    term: 'User Story',
    category: 'Process & Agile',
    definition:
      'A short description of a feature from the user’s point of view, typically written as “As a [user], I want [goal], so that [reason].”',
  },

  // Data & Metrics
  {
    term: 'A/B Test',
    category: 'Data & Metrics',
    definition:
      'An experiment that shows two (or more) versions of something to different, randomly assigned users, to measure which version actually performs better.',
  },
  {
    term: 'Activation Rate',
    category: 'Data & Metrics',
    definition:
      'The percentage of new users who reach a meaningful “aha” moment early in their experience — a strong predictor of whether they’ll stick around.',
  },
  {
    term: 'AOV (Average Order Value)',
    category: 'Data & Metrics',
    definition:
      'The average amount a customer spends per order, calculated as total revenue divided by number of orders — a quick read on whether purchase size is growing or shrinking.',
  },
  {
    term: 'ARPU (Average Revenue Per User)',
    category: 'Data & Metrics',
    definition:
      'Total revenue divided by the number of active users over a given period — a rough measure of how much value each user generates, on average.',
  },
  {
    term: 'CAC (Customer Acquisition Cost)',
    category: 'Data & Metrics',
    definition: 'How much it costs, on average, to acquire one new paying customer, across all marketing and sales spend.',
  },
  {
    term: 'CHS (Customer Health Score)',
    category: 'Data & Metrics',
    definition:
      'A composite score — usually blending usage, engagement, and support signals — that estimates how likely a customer is to renew, expand, or churn.',
  },
  {
    term: 'Churn Rate',
    category: 'Data & Metrics',
    definition:
      'The percentage of customers or users who stop using a product over a given period — the mirror image of retention.',
  },
  {
    term: 'Cohort Analysis',
    category: 'Data & Metrics',
    definition:
      'Grouping users by a shared starting point (like signup week) and tracking how their behaviour evolves over time, rather than looking at everyone as one blended average.',
  },
  {
    term: 'Conversion Rate',
    category: 'Data & Metrics',
    definition:
      'The percentage of people who complete a desired action — signing up, purchasing, upgrading — out of everyone who had the opportunity to.',
  },
  {
    term: 'CPL (Cost Per Lead)',
    category: 'Data & Metrics',
    definition:
      'How much it costs, on average, to generate one new lead through marketing spend — an earlier-funnel cousin of CAC, tracked before a lead ever becomes a paying customer.',
  },
  {
    term: 'CSAT (Customer Satisfaction)',
    category: 'Data & Metrics',
    definition:
      'A short-term satisfaction score gathered by asking users to rate a specific interaction or experience, typically on a simple numeric or star scale.',
  },
  {
    term: 'DAU / MAU (Daily / Monthly Active Users)',
    category: 'Data & Metrics',
    definition:
      'Counts of the unique users who engage with a product within a single day (DAU) or a rolling thirty-day window (MAU) — the baseline counts most other engagement metrics are built on.',
  },
  {
    term: 'GMV (Gross Merchandise Volume)',
    category: 'Data & Metrics',
    definition:
      'The total value of goods or services sold through a platform over a given period, before fees, discounts, or returns are deducted.',
  },
  {
    term: 'Gross Margin',
    category: 'Data & Metrics',
    definition:
      'The percentage of revenue left after subtracting the direct cost of delivering a product or service — a core signal of how profitable the underlying business actually is.',
  },
  {
    term: 'KPI (Key Performance Indicator)',
    category: 'Data & Metrics',
    definition: 'A specific, agreed metric used to track whether something important is on track, over time.',
  },
  {
    term: 'LTV / CLV (Customer Lifetime Value)',
    category: 'Data & Metrics',
    definition:
      'The total revenue a business can expect from one customer over the entire time they stay a customer — usually compared directly against CAC to judge whether growth is actually profitable.',
  },
  {
    term: 'NDR (Net Dollar Retention)',
    category: 'Data & Metrics',
    definition:
      'The percentage change in recurring revenue from an existing group of customers over a period, factoring in expansion, downgrades, and churn — also called Net Revenue Retention. A figure above 100% means existing customers are growing revenue even before any new ones are added.',
  },
  {
    term: 'North Star Metric',
    category: 'Data & Metrics',
    definition:
      "The single metric a team treats as the clearest proxy for the value it delivers to customers — the one number that, if it moves in the right direction, means real things are going well.",
  },
  {
    term: 'OKR (Objectives & Key Results)',
    category: 'Data & Metrics',
    definition:
      "A goal-setting framework pairing a qualitative Objective (what you want to achieve) with a small set of measurable Key Results (how you’ll know you got there).",
    seeAlso: { to: '/day/2', label: 'Day 2' },
  },
  {
    term: 'Retention Rate',
    category: 'Data & Metrics',
    definition: 'The percentage of users who keep coming back over a given period after they first arrive.',
  },
  {
    term: 'Session Duration',
    category: 'Data & Metrics',
    definition: 'How long a user spends actively engaged in a single session with a product, from open to close or timeout.',
  },
  {
    term: 'Stickiness (DAU/MAU Ratio)',
    category: 'Data & Metrics',
    definition:
      'DAU divided by MAU, expressed as a percentage — a measure of what share of a product’s monthly users come back on any given day.',
  },
  {
    term: 'Viral Coefficient',
    category: 'Data & Metrics',
    definition:
      'The average number of new users each existing user brings in through referrals. Above 1.0, growth compounds on its own; below 1.0, it still needs other channels to sustain itself.',
  },

  // Product & Growth
  {
    term: 'Go-To-Market (GTM)',
    category: 'Product & Growth',
    definition:
      'The plan for how a product actually reaches its customers at launch: positioning, pricing, channels, and the sequence of activities that gets it in front of the right people.',
  },
  {
    term: 'MVP (Minimum Viable Product)',
    category: 'Product & Growth',
    definition: 'The smallest version of a product that still delivers enough value to real users to generate genuine feedback and learning.',
  },
  {
    term: 'NPS (Net Promoter Score)',
    category: 'Product & Growth',
    definition:
      'A loyalty metric based on asking customers how likely they are to recommend a product, on a 0–10 scale, used as a rough proxy for satisfaction.',
  },
  {
    term: 'Product Lifecycle',
    category: 'Product & Growth',
    definition: 'The stages a product moves through, from introduction to the market through growth, maturity, and eventual decline or retirement.',
  },
  {
    term: 'Product-Led Growth (PLG)',
    category: 'Product & Growth',
    definition:
      'A go-to-market strategy where the product itself — not sales or marketing — is the primary driver of acquisition, conversion, and expansion, usually via a free trial or freemium model.',
  },
  {
    term: 'Product-Market Fit (PMF)',
    category: 'Product & Growth',
    definition:
      'The point at which a product satisfies real market demand strongly enough that growth starts to feel pulled by customers rather than pushed by the team.',
    seeAlso: { to: '/day/4', label: 'Day 4' },
  },
  {
    term: 'RICE Score',
    category: 'Product & Growth',
    definition: 'A prioritisation formula — Reach × Impact × Confidence ÷ Effort — used to rank competing ideas on a comparable numeric scale.',
  },
  {
    term: 'Roadmap',
    category: 'Product & Growth',
    definition: "A team’s plan for what it intends to build and in what order, ideally framed around outcomes and themes rather than fixed dates.",
    seeAlso: { to: '/day/3', label: 'Day 3' },
  },
  {
    term: 'SWOT',
    category: 'Product & Growth',
    definition:
      "A simple strategic planning tool that maps an organisation’s internal Strengths and Weaknesses against external Opportunities and Threats.",
  },
  {
    term: 'TAM / SAM / SOM',
    category: 'Product & Growth',
    definition:
      'A way of sizing a market in three nested layers: Total Addressable Market (everyone who could ever want this), Serviceable Available Market (who you could realistically reach), and Serviceable Obtainable Market (who you can realistically win).',
  },
  {
    term: 'Time to Value (TTV)',
    category: 'Product & Growth',
    definition:
      "How long it takes a new user to experience a product’s core benefit for the first time. A shorter TTV generally means stronger early engagement and retention.",
  },
  {
    term: 'Traffic Source Distribution',
    category: 'Product & Growth',
    definition:
      "A breakdown of where a product’s visitors or users actually come from — organic search, referrals, paid ads, direct — used to understand which channels are actually working.",
  },
]
